/* automatically generated by rust-bindgen 0.70.1 */
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]
#![allow(non_snake_case)]

use libc::{c_char, c_int, c_uint, c_void, FILE};

#[doc = "< No flag."]
pub const CQDB_NONE: c_uint = 0;
#[doc = "< A reverse lookup array is omitted."]
pub const CQDB_ONEWAY: c_uint = 1;
#[doc = "< An error has occurred."]
pub const CQDB_ERROR_OCCURRED: c_uint = 65536;

#[doc = "< Success."]
pub const CQDB_SUCCESS: c_int = 0;
#[doc = "< Unspecified error."]
pub const CQDB_ERROR: c_int = -1024;
#[doc = "< String not found."]
pub const CQDB_ERROR_NOTFOUND: c_int = -1023;
#[doc = "< Insufficient memory."]
pub const CQDB_ERROR_OUTOFMEMORY: c_int = -1022;
#[doc = "< Error in fwrite() operations."]
pub const CQDB_ERROR_FILEWRITE: c_int = -1021;
#[doc = "< Error in ftell() operations."]
pub const CQDB_ERROR_FILETELL: c_int = -1020;
#[doc = "< Error in fseek() operations."]
pub const CQDB_ERROR_FILESEEK: c_int = -1019;
#[doc = "< Invalid parameters."]
pub const CQDB_ERROR_INVALIDID: c_int = -1018;

#[doc = " CQDB Writer API\n\n    The CQDB Writer API constructs a CQDB chunk on a seekable stream."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tag_cqdb_writer {
    _unused: [u8; 0],
}
pub type cqdb_writer_t = tag_cqdb_writer;

extern "C" {
    #[doc = " Create a new CQDB writer on a seekable stream."]
    pub fn cqdb_writer(fp: *mut FILE, flag: c_int) -> *mut cqdb_writer_t;
}
extern "C" {
    #[doc = " Put a string/identifier association to the database."]
    pub fn cqdb_writer_put(
        dbw: *mut cqdb_writer_t,
        str_: *const c_char,
        id: c_int,
    ) -> c_int;
}
extern "C" {
    #[doc = " Close a CQDB writer."]
    pub fn cqdb_writer_close(dbw: *mut cqdb_writer_t) -> c_int;
}

#[doc = " CQDB Reader API\n\n    The CQDB reader API provides a read access to the database."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tag_cqdb {
    _unused: [u8; 0],
}
pub type cqdb_t = tag_cqdb;

extern "C" {
    #[doc = " Open a new CQDB reader on a memory block."]
    pub fn cqdb_reader(buffer: *const c_void, size: usize) -> *mut cqdb_t;
}
extern "C" {
    #[doc = " Delete the CQDB reader."]
    pub fn cqdb_delete(db: *mut cqdb_t);
}
extern "C" {
    #[doc = " Retrieve the identifier associated with a string."]
    pub fn cqdb_to_id(db: *mut cqdb_t, str_: *const c_char) -> c_int;
}
extern "C" {
    #[doc = " Retrieve the string associated with an identifier."]
    pub fn cqdb_to_string(db: *mut cqdb_t, id: c_int) -> *const c_char;
}
extern "C" {
    #[doc = " Get the number of associations in the database."]
    pub fn cqdb_num(db: *mut cqdb_t) -> c_int;
}
